# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markocupic\ContaoCustomGlobalOperation\:
        resource: ../src/
        exclude:
            - ../src/ContaoManager/
            - ../src/DependencyInjection/
            - ../src/MarkocupicContaoCustomGlobalOperation.php
